meta_product_name: "Food Majordome"
meta_title: "Food Majordome - Never waist your time again doing menus and shopping !"
meta_description: "Food Majordome is a srvice elaborated with care to help you to organise your weekly meal plan. Just tell us your preferences, we suggest you menus and compile your shopping list for you!"
meta_image: "cover.jpg" # should exist in `app/assets/images/`